import { Medal, Rank, User } from "./types";

export const ranks: Rank[] = [
  {
    id: "recruta",
    name: "Recruta",
    src: "https://upload.wikimedia.org/wikipedia/commons/9/96/G01-EB_Soldado.svg",
    rarity: "comum",
  },
  {
    id: "soldado",
    name: "Soldado",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/47/G03-EB_Terceiro_Sargento.svg",
    rarity: "raro",
  },
  {
    id: "cabo",
    name: "Cabo",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/47/G03-EB_Terceiro_Sargento.svg",
    rarity: "epico",
  },
  {
    id: "sargento",
    name: "Sargento",
    src: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Brazil-Army-OF-1a.svg",
    rarity: "raro",
  },
  {
    id: "tenente",
    name: "Tenente",
    src: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Brazil-Army-OF-1b.svg",
    rarity: "epico",
  },
  {
    id: "capitao",
    name: "Capitão",
    src: "https://upload.wikimedia.org/wikipedia/commons/8/88/Brazil-Army-OF-7.svg",
    rarity: "raro",
  },
  {
    id: "major",
    name: "Major",
    src: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Brazil-Army-OF-8.svg",
    rarity: "epico",
  },
  {
    id: "coronel",
    name: "Coronel",
    src: "https://upload.wikimedia.org/wikipedia/commons/2/23/Brazil-Army-OF-9.svg",
    rarity: "raro",
  },
  {
    id: "general",
    name: "General",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Brazil-Army-OF-10.svg",
    rarity: "epico",
  },
];

export const medals: Medal[] = [
  {
    id: "killstreak-20",
    name: "Imparável",
    description: "20 kills sem morrer",
    criteria: "Consiga 20 abates consecutivos sem ser eliminado em uma partida",
    icon: "🔥",
    rarity: "lendario",
  },
  {
    id: "revive-master",
    name: "Médico de Campo",
    description: "100 revives em uma partida",
    criteria: "Reviva 100 ou mais companheiros em uma única partida",
    icon: "⚕️",
    rarity: "epico",
  },
  {
    id: "sniper-elite",
    name: "Franco-Atirador Elite",
    description: "10 headshots consecutivos",
    criteria: "Consiga 10 headshots consecutivos com sniper",
    icon: "🎯",
    rarity: "epico",
  },
  {
    id: "objective-hero",
    name: "Herói do Objetivo",
    description: "Capture 50 objetivos",
    criteria: "Capture ou defenda 50 objetivos em partidas ranqueadas",
    icon: "🏆",
    rarity: "epico",
  },
  {
    id: "team-player",
    name: "Jogador de Equipe",
    description: "500 assists",
    criteria: "Acumule 500 assistências no total",
    icon: "🤝",
    rarity: "raro",
  },
  {
    id: "vehicle-destroyer",
    name: "Destruidor de Veículos",
    description: "Destrua 100 veículos",
    criteria: "Destrua 100 veículos inimigos",
    icon: "💥",
    rarity: "epico",
  },
  {
    id: "first-blood",
    name: "Primeira Sangue",
    description: "First blood em 50 partidas",
    criteria: "Consiga o primeiro kill em 50 partidas diferentes",
    icon: "⚡",
    rarity: "raro",
  },
  {
    id: "veteran",
    name: "Veterano",
    description: "1000 horas jogadas",
    criteria: "Acumule 1000 horas de jogo",
    icon: "🎖️",
    rarity: "lendario",
  },
  {
    id: "ace-pilot",
    name: "Ás dos Céus",
    description: "50 kills aéreos",
    criteria: "Consiga 50 abates usando veículos aéreos",
    icon: "✈️",
    rarity: "epico",
  },
  {
    id: "clutch-master",
    name: "Clutch Master",
    description: "Vença 1v5 em 10 partidas",
    criteria: "Vença situações 1v5 em 10 partidas ranqueadas",
    icon: "👑",
    rarity: "lendario",
  },
];
