import { Medal, Player, Rank } from "./types";

export const ranks: Rank[] = [
  {
    id: "recruta",
    name: "Recruta",
    description: "Recruta",
    src: "https://upload.wikimedia.org/wikipedia/commons/9/96/G01-EB_Soldado.svg",
    rarity: "comum",
  },
  {
    id: "soldado",
    name: "Soldado",
    description: "Soldado",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/47/G03-EB_Terceiro_Sargento.svg",
    rarity: "raro",
  },
  {
    id: "cabo",
    name: "Cabo",
    description: "Cabo",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/47/G03-EB_Terceiro_Sargento.svg",
    rarity: "épico",
  },
  {
    id: "sargento",
    name: "Sargento",
    description: "Sargento",
    src: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Brazil-Army-OF-1a.svg",
    rarity: "raro",
  },
  {
    id: "tenente",
    name: "Tenente",
    description: "Tenente",
    src: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Brazil-Army-OF-1b.svg",
    rarity: "épico",
  },
  {
    id: "capitao",
    name: "Capitão",
    description: "Capitão",
    src: "https://upload.wikimedia.org/wikipedia/commons/8/88/Brazil-Army-OF-7.svg",
    rarity: "raro",
  },
  {
    id: "major",
    name: "Major",
    description: "Major",
    src: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Brazil-Army-OF-8.svg",
    rarity: "épico",
  },
  {
    id: "coronel",
    name: "Coronel",
    description: "Coronel",
    src: "https://upload.wikimedia.org/wikipedia/commons/2/23/Brazil-Army-OF-9.svg",
    rarity: "raro",
  },
  {
    id: "general",
    name: "General",
    description: "General",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Brazil-Army-OF-10.svg",
    rarity: "épico",
  },
];

export const medals: Medal[] = [
  {
    id: "killstreak-20",
    name: "Imparável",
    description: "20 kills sem morrer",
    criteria: "Consiga 20 abates consecutivos sem ser eliminado em uma partida",
    icon: "🔥",
    rarity: "lendário",
  },
  {
    id: "revive-master",
    name: "Médico de Campo",
    description: "100 revives em uma partida",
    criteria: "Reviva 100 ou mais companheiros em uma única partida",
    icon: "⚕️",
    rarity: "épico",
  },
  {
    id: "sniper-elite",
    name: "Franco-Atirador Elite",
    description: "10 headshots consecutivos",
    criteria: "Consiga 10 headshots consecutivos com sniper",
    icon: "🎯",
    rarity: "épico",
  },
  {
    id: "objective-hero",
    name: "Herói do Objetivo",
    description: "Capture 50 objetivos",
    criteria: "Capture ou defenda 50 objetivos em partidas ranqueadas",
    icon: "🏆",
    rarity: "raro",
  },
  {
    id: "team-player",
    name: "Jogador de Equipe",
    description: "500 assists",
    criteria: "Acumule 500 assistências no total",
    icon: "🤝",
    rarity: "raro",
  },
  {
    id: "vehicle-destroyer",
    name: "Destruidor de Veículos",
    description: "Destrua 100 veículos",
    criteria: "Destrua 100 veículos inimigos",
    icon: "💥",
    rarity: "épico",
  },
  {
    id: "first-blood",
    name: "Primeira Sangue",
    description: "First blood em 50 partidas",
    criteria: "Consiga o primeiro kill em 50 partidas diferentes",
    icon: "⚡",
    rarity: "raro",
  },
  {
    id: "veteran",
    name: "Veterano",
    description: "1000 horas jogadas",
    criteria: "Acumule 1000 horas de jogo",
    icon: "🎖️",
    rarity: "lendário",
  },
  {
    id: "ace-pilot",
    name: "Ás dos Céus",
    description: "50 kills aéreos",
    criteria: "Consiga 50 abates usando veículos aéreos",
    icon: "✈️",
    rarity: "épico",
  },
  {
    id: "clutch-master",
    name: "Clutch Master",
    description: "Vença 1v5 em 10 partidas",
    criteria: "Vença situações 1v5 em 10 partidas ranqueadas",
    icon: "👑",
    rarity: "lendário",
  },
];

export const players: Player[] = [
  {
    id: "1",
    name: "DarkWolf",
    eaId: "DarkWolf#4521",
    rank_id: "recruta",
    platform: "PC",
    avatar: "/tactical-military-avatar-dark-wolf.jpg",
    bio: "Veterano de BF desde 2002. Especialista em sniper e táticas de longo alcance.",
    stats: {
      kills: 15420,
      deaths: 6234,
      kd: 2.47,
      assists: 3421,
      revives: 1876,
      matches: 1543,
      hoursPlayed: 847,
      winRate: 62.4,
      headshots: 4231,
      longestKillStreak: 32,
    },
    medals: [
      "killstreak-20",
      "sniper-elite",
      "veteran",
      "revive-master",
      "clutch-master",
    ],
    joinedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "PhoenixRising",
    eaId: "PhoenixRising#8821",
    rank_id: "general",
    platform: "PlayStation",
    avatar: "/tactical-military-avatar-phoenix.jpg",
    bio: "Jogador agressivo focado em objetivos. MVP em 80% das partidas ranqueadas.",
    stats: {
      kills: 18765,
      deaths: 7123,
      kd: 2.63,
      assists: 4567,
      revives: 2134,
      matches: 1876,
      hoursPlayed: 1024,
      winRate: 65.2,
      headshots: 5432,
      longestKillStreak: 28,
    },
    medals: [
      "killstreak-20",
      "revive-master",
      "veteran",
      "first-blood",
      "ace-pilot",
    ],
    joinedAt: "2024-01-10",
  },
  {
    id: "3",
    name: "ShadowStrike",
    eaId: "ShadowStrike#3421",
    rank_id: "coronel",
    platform: "Xbox",
    avatar: "/tactical-military-avatar-shadow.jpg",
    bio: "Médico de campo dedicado. Sempre priorizo reviver os companheiros em combate.",
    stats: {
      kills: 12340,
      deaths: 5678,
      kd: 2.17,
      assists: 2891,
      revives: 3421,
      matches: 1234,
      hoursPlayed: 687,
      winRate: 58.3,
      headshots: 3421,
      longestKillStreak: 25,
    },
    medals: [
      "revive-master",
      "team-player",
      "objective-hero",
      "vehicle-destroyer",
      "team-player",
    ],
    joinedAt: "2024-02-20",
  },
  {
    id: "4",
    name: "IronViper",
    eaId: "IronViper#7654",
    rank_id: "major",
    platform: "PC",
    avatar: "/tactical-military-avatar-viper.jpg",
    bio: "Especialista em destruição de veículos e suporte anti-tanque.",
    stats: {
      kills: 9876,
      deaths: 4532,
      kd: 2.18,
      assists: 2134,
      revives: 987,
      matches: 987,
      hoursPlayed: 543,
      winRate: 56.7,
      headshots: 2765,
      longestKillStreak: 22,
    },
    medals: ["sniper-elite", "first-blood", "vehicle-destroyer"],
    joinedAt: "2024-03-05",
  },
  {
    id: "5",
    name: "ThunderBolt",
    eaId: "ThunderBolt#2109",
    rank_id: "capitao",
    platform: "PC",
    avatar: "/tactical-military-avatar-thunder.jpg",
    bio: "Jogador equilibrado focado em captura de objetivos e trabalho em equipe.",
    stats: {
      kills: 8765,
      deaths: 4123,
      kd: 2.13,
      assists: 1987,
      revives: 876,
      matches: 876,
      hoursPlayed: 456,
      winRate: 54.2,
      headshots: 2341,
      longestKillStreak: 20,
    },
    medals: ["team-player", "objective-hero", "first-blood"],
    joinedAt: "2024-03-15",
  },
  {
    id: "6",
    name: "NightHawk",
    eaId: "NightHawk#5543",
    rank_id: "tenente",
    platform: "PlayStation",
    avatar: "/tactical-military-avatar-hawk.jpg",
    bio: "Novo no clã, mas sempre dando o meu melhor. Focado em evoluir constantemente.",
    stats: {
      kills: 7654,
      deaths: 3876,
      kd: 1.97,
      assists: 1654,
      revives: 765,
      matches: 765,
      hoursPlayed: 398,
      winRate: 52.1,
      headshots: 1987,
      longestKillStreak: 18,
    },
    medals: ["team-player", "objective-hero"],
    joinedAt: "2024-04-01",
  },
];
